services:
  app:
    build:
      context: .
      args:
        VITE_CDN_BASE_URL: ${VITE_CDN_BASE_URL}
        VITE_LOGIN_BG_PC: ${VITE_LOGIN_BG_PC}
        VITE_LOGIN_BG_MOBILE: ${VITE_LOGIN_BG_MOBILE}
        VITE_AUTH_TIMEOUT_MINUTES: ${VITE_AUTH_TIMEOUT_MINUTES}
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ${LOCAL_PATH:-.}:/app/local
    dns:
      - 8.8.8.8
      - 114.114.114.114
    restart: unless-stopped
