services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ${LOCAL_PATH:-.}:/app/local
    dns:
      - 8.8.8.8
      - 114.114.114.114
    restart: unless-stopped