services:
  app:
    user: "0:0" # Please replace `0:0` with the actual user ID and group ID you want to use.
    build:
      context: .
      args:
        VITE_CDN_BASE_URL: ${VITE_CDN_BASE_URL}
        VITE_LOGIN_BG_PC: ${VITE_LOGIN_BG_PC}
        VITE_LOGIN_BG_MOBILE: ${VITE_LOGIN_BG_MOBILE}
        VITE_AUTH_TIMEOUT_MINUTES: ${VITE_AUTH_TIMEOUT_MINUTES}
        VITE_SITE_TITLE: ${VITE_SITE_TITLE}
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ${LOCAL_PATH:-/tmp}:/app/local
    restart: unless-stopped
